apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-entwicklungstemplate-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: k8s_admins@klosebrothers.de
    privateKeySecretRef:
      name: letsencrypt-entwicklungstemplate-prod
    solvers:
      - http01:
          ingress:
            class: nginx