apiVersion: v1
kind: Service
metadata:
  name: kb-app-deployment
spec:
  selector:
    app: kb-app-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kb-app-ingress-resource-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-kb-app-prod"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
spec:
  tls:
    - hosts:
        - kb-app.klosebrothers.de
      secretName: letsencrypt-kb-app-prod
  rules:
    - host: kb-app.klosebrothers.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kb-app-deployment
                port:
                  number: 8080
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kb-app-oauth2-proxy
spec:
  tls:
    - hosts:
        - kb-app.klosebrothers.de
      secretName: letsencrypt-kb-app-prod
  rules:
    - host: kb-app.klosebrothers.de
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: kb-google-oauth2-proxy
                port:
                  number: 4180
  ingressClassName: nginx